name: Build and Test Docker Image

on:
  pull_request:
    branches:
      - master
    paths:
      - "ubuntu/**"
      - ".github/workflows/**"
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

env:
  DOCKER_USERNAME: tiryoh

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [xenial, bionic]
        target: [core, base, devel]
    steps:
      - uses: actions/checkout@master

      - name: Build docker image
        env:
          DISTRO: ${{ matrix.distro }}
          TARGET: ${{ matrix.target }}
        run: |
          cd ubuntu/$DISTRO/$TARGET && docker build -t ubuntu:$DISTRO-$TARGET .

      - name: Install trivy
        run: |
          sudo apt-get install apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Vulnerability Scan with Trivy
        env:
          DISTRO: ${{ matrix.distro }}
          TARGET: ${{ matrix.target }}
        run: |
          mkdir -p build_log
          trivy --exit-code 0 --severity HIGH --no-progress ubuntu:${DISTRO}-${TARGET} | tee ./build_log/trivy_log-HIGH.txt
          trivy --exit-code 0 --severity CRITICAL --no-progress ubuntu:${DISTRO}-${TARGET} | tee ./build_log/trivy_log-CRITICAL.txt

      - name: Rename docker images
        env:
          DISTRO: ${{ matrix.distro }}
          TARGET: ${{ matrix.target }}
        run: |
          TIMESTAMP=$(date '+%Y%m%dT%H%M')
          if [[ "$DISTRO" == "bionic" ]] && [[ "$TARGET" == "base" ]]; then IS_LATEST="true"; else IS_LATEST="false"; fi
          IMAGE_TAG=$DISTRO-$TARGET
          docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:$IMAGE_TAG
          docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:$IMAGE_TAG-$TIMESTAMP
          if [[ "$TARGET" == "core" ]]; then
            docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:$DISTRO-bash
          fi
          if [[ "$TARGET" == "base" ]]; then
            docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:$DISTRO
          fi
          if [[ "$TARGET" == "devel" ]]; then
            docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:dev-$DISTRO
            docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:$DISTRO-dev
          fi
          if [[ "$IS_LATEST" == "true" ]]; then
          	docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:latest
          fi

      - name: List docker images
        run: |
          mkdir -p build_log
          docker image ls "$DOCKER_USERNAME/*" | tee ./build_log/docker_images.txt

      - uses: actions/upload-artifact@v1
        with:
          name: build_log-${{ matrix.distro }}-${{ matrix.target }}
          path: build_log
