name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - "ubuntu/**"
      - ".github/workflows/**"
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

env:
  DOCKER_USERNAME: tiryoh

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "[Skip CI] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"

  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    strategy:
      matrix:
        distro: [xenial, bionic]
        target: [core, base, devel]
    steps:
      - uses: actions/checkout@master

      - name: Build docker image
        env:
          DISTRO: ${{ matrix.distro }}
          TARGET: ${{ matrix.target }}
        run: |
          cd ubuntu/$DISTRO/$TARGET && docker build -t ubuntu:$DISTRO-$TARGET .

      - name: Rename docker images
        env:
          DISTRO: ${{ matrix.distro }}
          TARGET: ${{ matrix.target }}
        run: |
          TIMESTAMP=$(date '+%Y%m%dT%H%M')
          if [[ "$DISTRO" == "bionic" ]] && [[ "$TARGET" == "base" ]]; then IS_LATEST="true"; else IS_LATEST="false"; fi
          IMAGE_TAG=$DISTRO-$TARGET
          docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:$IMAGE_TAG
          docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:$IMAGE_TAG-$TIMESTAMP
          if [[ "$TARGET" == "core" ]]; then
            docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:$DISTRO-bash
          fi
          if [[ "$TARGET" == "base" ]]; then
            docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:$DISTRO
          fi
          if [[ "$TARGET" == "devel" ]]; then
            docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:dev-$DISTRO
            docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:$DISTRO-dev
          fi
          if [[ "$IS_LATEST" == "true" ]]; then
          	docker tag ubuntu:$IMAGE_TAG $DOCKER_USERNAME/ubuntu:latest
          fi

      - name: Push docker image to Docker Hub
        env:
          DISTRO: ${{ matrix.distro }}
          TARGET: ${{ matrix.target }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin > /dev/null 2>&1
          docker image ls "tiryoh/*" | tail -n +2 | awk '{print $1":"$2}' | xargs -I{} docker push {}
